name: bioscann
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - alembic>=1.13.2
  - aom>=3.5.0
  - attrs>=23.2.0
  - aws-c-auth>=0.7.22
  - aws-c-cal>=0.6.15
  - aws-c-common>=0.9.23
  - aws-c-compression>=0.2.18
  - aws-c-event-stream>=0.4.2
  - aws-c-http>=0.8.2
  - aws-c-io>=0.14.9
  - aws-c-mqtt>=0.10.4
  - aws-c-s3>=0.5.10
  - aws-c-sdkutils>=0.1.16
  - aws-checksums>=0.1.18
  - aws-crt-cpp>=0.26.12
  - bcrypt>=4.1.3
  - blinker>=1.8.2
  - blosc>=1.21.5
  - boost-cpp>=1.78.0
  - brotli>=1.0.9
  - brotli-bin>=1.0.9
  - brotli-python>=1.0.9
  - brunsli>=0.1
  - bzip2>=1.0.8
  - c-ares>=1.28.1
  - c-blosc2>=2.12.0
  - ca-certificates>=2024.7.4
  - cairo>=1.16.0
  - certifi>=2024.6.2
  - cffi>=1.16.0
  - cfitsio>=4.2.0
  - charls>=2.4.2
  - charset-normalizer>=3.3.2
  - click>=8.1.7
  - click-plugins>=1.1.1
  - cligj>=0.7.2
  - cloudpickle>=3.0.0
  - configparser>=7.0.0
  - cryptography>=41.0.7
  - databricks-cli>=0.17.3
  - dav1d>=1.2.1
  - docker-py>=7.1.0
  - entrypoints>=0.4
  - expat>=2.6.2
  - filelock>=3.15.4
  - fiona>=1.9.3
  - flask>=3.0.3
  - fmt>=10.2.1
  - font-ttf-dejavu-sans-mono>=2.37
  - font-ttf-inconsolata>=3.000
  - font-ttf-source-code-pro>=2.038
  - font-ttf-ubuntu>=0.83
  - fontconfig>=2.14.2
  - fonts-conda-ecosystem>=1
  - fonts-conda-forge>=1
  - freetype>=2.12.1
  - freexl>=1.0.6
  - fsspec>=2024.6.1
  - gdal>=3.7.1
  - geos>=3.12.0
  - geotiff>=1.7.1
  - gettext>=0.22.5
  - gettext-tools>=0.22.5
  - giflib>=5.2.2
  - gitdb>=4.0.11
  - gitpython>=3.1.43
  - gmp>=6.3.0
  - gmpy2>=2.1.5
  - gorilla>=0.4.0
  - greenlet>=3.0.3
  - gunicorn>=22.0.0
  - h2>=4.1.0
  - hdf4>=4.2.15
  - hdf5>=1.14.1
  - hpack>=4.0.0
  - hyperframe>=6.0.1
  - icu>=72.1
  - idna>=3.7
  - imagecodecs>=2023.1.23
  - importlib-metadata>=8.0.0
  - importlib_resources>=6.4.0
  - itsdangerous>=2.2.0
  - jinja2>=3.1.4
  - json-c>=0.16
  - jxrlib>=1.1
  - kealib>=1.5.1
  - krb5>=1.21.2
  - lcms2>=2.15
  - lerc>=4.0.0
  - libabseil>=20240116.2
  - libaec>=1.1.3
  - libarchive>=3.6.2
  - libasprintf>=0.22.5
  - libasprintf-devel>=0.22.5
  - libavif>=0.11.1
  - libblas>=3.9.0
  - libbrotlicommon>=1.0.9
  - libbrotlidec>=1.0.9
  - libbrotlienc>=1.0.9
  - libcblas>=3.9.0
  - libcrc32c>=1.1.2
  - libcurl>=8.4.0
  - libcxx>=17.0.6
  - libdeflate>=1.18
  - libedit>=3.1.20191231
  - libev>=4.33
  - libexpat>=2.6.2
  - libffi>=3.4.2
  - libgdal>=3.7.1
  - libgettextpo>=0.22.5
  - libgettextpo-devel>=0.22.5
  - libgfortran>=5.0.0
  - libgfortran5>=13.2.0
  - libglib>=2.78.1
  - libiconv>=1.17
  - libintl>=0.22.5
  - libintl-devel>=0.22.5
  - libjpeg-turbo>=2.1.5.1
  - libkml>=1.3.0
  - liblapack>=3.9.0
  - libnetcdf>=4.9.2
  - libnghttp2>=1.58.0
  - libopenblas>=0.3.27
  - libpng>=1.6.43
  - libpq>=15.4
  - libprotobuf>=4.25.3
  - libre2-11>=2023.09.01
  - librttopo>=1.1.0
  - libsodium>=1.0.18
  - libspatialite>=5.0.1
  - libsqlite>=3.46.0
  - libssh2>=1.11.0
  - libtiff>=4.5.1
  - libtorch>=2.3.1
  - libuv>=1.48.0
  - libwebp-base>=1.4.0
  - libxcb>=1.15
  - libxml2>=2.11.5
  - libzip>=1.10.1
  - libzlib>=1.3.1
  - libzopfli>=1.0.3
  - llvm-openmp>=18.1.8
  - lz4-c>=1.9.4
  - lzo>=2.10
  - mako>=1.3.5
  - markupsafe>=2.1.5
  - mlflow>=1.2.0
  - mpc>=1.3.1
  - mpfr>=4.2.1
  - mpmath>=1.3.0
  - munch>=4.0.0
  - ncurses>=6.5
  - networkx>=2.8.8
  - nomkl>=1.0
  - nspr>=4.35
  - nss>=3.102
  - numpy>=1.24.4
  - oauthlib>=3.2.2
  - openjpeg>=2.5.0
  - openssl>=3.1.6
  - packaging>=24.1
  - pandas>=2.0.3
  - paramiko>=3.4.0
  - pcre2>=10.40
  - pillow>=9.5.0
  - pip>=24.0
  - pixman>=0.43.4
  - poppler>=23.07.0
  - poppler-data>=0.4.12
  - postgresql>=15.4
  - proj>=9.2.1
  - protobuf>=4.25.3
  - pthread-stubs>=0.4
  - pycparser>=2.22
  - pyjwt>=2.8.0
  - pynacl>=1.5.0
  - pysocks>=1.7.1
  - python>=3.8.18
  - python-dateutil>=2.9.0
  - python-tzdata>=2024.1
  - python_abi>=3.8
  - pytorch>=2.3.1
  - pytz>=2024.1
  - pywin32-on-windows>=0.1.0
  - pyyaml>=6.0.1
  - querystring_parser>=1.2.4
  - re2>=2023.09.01
  - readline>=8.2
  - requests>=2.32.3
  - setuptools>=70.1.1
  - simplejson>=3.19.2
  - six>=1.16.0
  - sleef>=3.5.1
  - smmap>=5.0.0
  - snappy>=1.1.10
  - spdlog>=1.13.0
  - sqlalchemy>=2.0.31
  - sqlite>=3.46.0
  - sqlparse>=0.5.0
  - sympy>=1.12.1
  - tabulate>=0.9.0
  - tiledb>=2.16.3
  - tk>=8.6.13
  - torchvision>=0.14.1
  - typing-extensions>=4.12.2
  - typing_extensions>=4.12.2
  - tzcode>=2024a
  - tzdata>=2024a
  - uriparser>=0.9.8
  - urllib3>=2.2.2
  - websocket-client>=1.8.0
  - werkzeug>=3.0.3
  - wheel>=0.43.0
  - xerces-c>=3.2.4
  - xorg-libxau>=1.0.11
  - xorg-libxdmcp>=1.1.3
  - xz>=5.2.6
  - yaml>=0.2.5
  - zfp>=1.0.1
  - zipp>=3.19.2
  - zlib>=1.3.1
  - zlib-ng>=2.0.7
  - zstandard>=0.22.0
  - zstd>=1.5.6
  - pip:
    - absl-py>=2.1.0
    - appnope>=0.1.4
    - asttokens>=2.4.1
    - backcall>=0.2.0
    - cachetools>=5.3.3
    - comm>=0.2.2
    - cycler>=0.12.1
    - debugpy>=1.8.2
    - decorator>=5.1.1
    - executing>=2.0.1
    - exifread>=2.3.2
    - fonttools>=4.53.1
    - geopandas>=0.13.2
    - google-auth>=2.31.0
    - google-auth-oauthlib>=1.0.0
    - grpcio>=1.64.1
    - imageio>=2.34.2
    - ipykernel>=6.29.5
    - ipython>=8.12.3
    - jedi>=0.19.1
    - joblib>=1.4.2
    - jupyter-client>=8.6.2
    - jupyter-core>=5.7.2
    - kiwisolver>=1.4.5
    - lazy-loader>=0.4
    - markdown>=3.6
    - matplotlib>=3.5.1
    - matplotlib-inline>=0.1.7
    - nest-asyncio>=1.6.0
    - opencv-python>=4.5.5.64
    - parso>=0.8.4
    - pexpect>=4.9.0
    - pickleshare>=0.7.5
    - platformdirs>=4.2.2
    - prompt-toolkit>=3.0.47
    - psutil>=6.0.0
    - ptyprocess>=0.7.0
    - pure-eval>=0.2.2
    - pyasn1>=0.6.0
    - pyasn1-modules>=0.4.0
    - pygments>=2.18.0
    - pyparsing>=3.1.2
    - pyproj>=3.5.0
    - pywavelets>=1.4.1
    - pyzmq>=26.0.3
    - requests-oauthlib>=2.0.0
    - rsa>=4.9
    - rtree>=1.0.0
    - scikit-image>=0.21.0
    - scikit-learn>=1.3.2
    - scipy>=1.10.1
    - shapely>=1.8.4
    - stack-data>=0.6.3
    - sweref99>=0.2
    - tensorboard>=2.14.0
    - tensorboard-data-server>=0.7.2
    - threadpoolctl>=3.5.0
    - tifffile>=2023.7.10
    - tornado>=6.4.1
    - tqdm>=4.64.1
    - traitlets>=5.14.3
    - wcwidth>=0.2.13

